spring.application.name=spring-learn-jwt

jwt.secret=aSuperSecretKeyForSpringLearnJWTAuthenticationWhichIsLongEnoughForHS256
jwt.token.validity=18000000

logging.level.com.cognizant.spring_learn_jwt=DEBUG
logging.level.org.springframework.security=DEBUG
